import fs from "fs-extra";
import path from "node:path";

const MARKER_FILE = ".doccupine-generated.json";
const SAFE_UNOWNED_FILES = new Set([".DS_Store", ".gitkeep", ".env"]);

function isSafeUnownedEntry(name: string): boolean {
  return SAFE_UNOWNED_FILES.has(name) || name.startsWith(".env.");
}

export function isPathInside(parent: string, candidate: string): boolean {
  const relative = path.relative(path.resolve(parent), path.resolve(candidate));
  return (
    relative === "" ||
    (relative !== ".." &&
      !relative.startsWith(`..${path.sep}`) &&
      !path.isAbsolute(relative))
  );
}

export function resolveWithin(root: string, ...segments: string[]): string {
  const resolvedRoot = path.resolve(root);
  const candidate = path.resolve(resolvedRoot, ...segments);
  if (!isPathInside(resolvedRoot, candidate)) {
    throw new Error(
      `Refusing to write outside generated output: ${candidate} is not within ${resolvedRoot}`,
    );
  }
  return candidate;
}

async function looksLikeLegacyGeneratedApp(
  outputDir: string,
): Promise<boolean> {
  try {
    const packagePath = path.join(outputDir, "package.json");
    if (!(await fs.pathExists(packagePath))) return false;
    const packageJson = (await fs.readJson(packagePath)) as {
      name?: unknown;
      private?: unknown;
    };
    return (
      packageJson.name === "doccupine" &&
      packageJson.private === true &&
      (await fs.pathExists(path.join(outputDir, "components"))) &&
      (await fs.pathExists(path.join(outputDir, "app")))
    );
  } catch {
    return false;
  }
}

/**
 * Claims an empty output directory, recognizes directories generated by older
 * Doccupine versions, and refuses to overwrite arbitrary existing projects.
 */
export async function claimOutputDirectory(outputDir: string): Promise<void> {
  await fs.ensureDir(outputDir);
  const markerPath = path.join(outputDir, MARKER_FILE);

  if (await fs.pathExists(markerPath)) {
    try {
      const marker = (await fs.readJson(markerPath)) as { generator?: unknown };
      if (marker.generator === "doccupine") return;
    } catch {
      // Fall through to the refusal below: a corrupt marker proves no ownership.
    }
    throw new Error(
      `Refusing to use ${outputDir}: ${MARKER_FILE} is invalid. Restore or remove the directory manually.`,
    );
  }

  const entries = await fs.readdir(outputDir);
  const canClaim =
    entries.every(isSafeUnownedEntry) ||
    (await looksLikeLegacyGeneratedApp(outputDir));
  if (!canClaim) {
    throw new Error(
      `Refusing to overwrite non-empty directory ${outputDir}. Choose an empty outputDir or a Doccupine-generated directory.`,
    );
  }

  await fs.writeJson(
    markerPath,
    { generator: "doccupine", schemaVersion: 1 },
    { spaces: 2, EOL: "\n" },
  );
}
