export const packageJsonTemplate =
  JSON.stringify(
    {
      name: "doccupine",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "tsx scripts/build-docs-index.mts && next build",
        start: "next start",
        lint: "eslint .",
        format: "prettier --write .",
        "format:check": "prettier --check .",
        "type-check": "tsgo --noEmit",
      },
      dependencies: {
        "@langchain/anthropic": "^1.5.8",
        "@langchain/core": "^1.2.9",
        "@langchain/google-genai": "^2.3.0",
        "@langchain/openai": "^1.5.10",
        "@mdx-js/react": "^3.1.1",
        "@modelcontextprotocol/sdk": "^1.30.0",
        "beautiful-mermaid": "^1.1.3",
        "cherry-styled-components": "^0.2.16",
        langchain: "^1.5.10",
        "lucide-react": "^1.33.0",
        minisearch: "^7.2.0",
        next: "16.3.2",
        "next-mdx-remote": "^6.0.0",
        "posthog-js": "^1.418.10",
        "posthog-node": "^5.50.0",
        react: "19.2.8",
        "react-dom": "19.2.8",
        "rehype-highlight": "^7.0.2",
        "rehype-parse": "^9.0.1",
        "rehype-stringify": "^10.0.1",
        "remark-gfm": "^4.0.1",
        "styled-components": "^6.5.3",
        unified: "^11.0.5",
        zod: "^4.4.3",
      },
      devDependencies: {
        "@next/env": "16.3.2",
        "@next/eslint-plugin-next": "16.3.2",
        "@types/node": "^26",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        "@typescript-eslint/eslint-plugin": "^8.67.0",
        "@typescript-eslint/parser": "^8.67.0",
        "@typescript/native-preview": "^7.0.0-dev.20260707.2",
        eslint: "^10",
        "eslint-plugin-import": "^2.32.0",
        "eslint-plugin-jsx-a11y": "^6.10.2",
        "eslint-plugin-react": "^7.37.5",
        "eslint-plugin-react-hooks": "^7.1.1",
        globals: "^17.11.0",
        prettier: "^3.9.6",
        tsx: "^4.23.12",
        typescript: "npm:@typescript/typescript6@^6.0.2",
      },
    },
    null,
    2,
  ) + "\n";
