export const packageJsonTemplate =
  JSON.stringify(
    {
      name: "doccupine",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "eslint .",
        format: "prettier --write .",
      },
      dependencies: {
        "@langchain/anthropic": "^1.4.0",
        "@langchain/core": "^1.1.48",
        "@langchain/google-genai": "^2.1.31",
        "@langchain/openai": "^1.4.7",
        "@mdx-js/react": "^3.1.1",
        "@modelcontextprotocol/sdk": "^1.29.0",
        "@posthog/react": "^1.10.1",
        "cherry-styled-components": "^0.1.17",
        langchain: "^1.4.4",
        "lucide-react": "^1.17.0",
        minisearch: "^7.2.0",
        next: "16.2.9",
        "next-mdx-remote": "^6.0.0",
        "posthog-js": "^1.384.1",
        "posthog-node": "^5.36.10",
        react: "19.2.7",
        "react-dom": "19.2.7",
        "rehype-highlight": "^7.0.2",
        "rehype-parse": "^9.0.1",
        "rehype-stringify": "^10.0.1",
        "remark-gfm": "^4.0.1",
        "styled-components": "^6.4.2",
        unified: "^11.0.5",
        zod: "^4.4.3",
      },
      devDependencies: {
        "@types/node": "^25",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        "baseline-browser-mapping": "^2.10.35",
        eslint: "^9",
        "eslint-config-next": "16.2.9",
        prettier: "^3.8.4",
        typescript: "^6",
      },
    },
    null,
    2,
  ) + "\n";
