export const packageJsonTemplate =
  JSON.stringify(
    {
      name: "doccupine",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "eslint .",
        format: "prettier --write .",
      },
      dependencies: {
        "@langchain/anthropic": "^1.3.27",
        "@langchain/core": "^1.1.41",
        "@langchain/google-genai": "^2.1.28",
        "@langchain/openai": "^1.4.4",
        "@mdx-js/react": "^3.1.1",
        "@modelcontextprotocol/sdk": "^1.29.0",
        "@posthog/react": "^1.9.0",
        "cherry-styled-components": "^0.1.17",
        langchain: "^1.3.4",
        "lucide-react": "^1.9.0",
        minisearch: "^7.2.0",
        next: "16.2.4",
        "next-mdx-remote": "^6.0.0",
        "posthog-js": "^1.371.2",
        "posthog-node": "^5.30.0",
        react: "19.2.5",
        "react-dom": "19.2.5",
        "rehype-highlight": "^7.0.2",
        "rehype-parse": "^9.0.1",
        "rehype-stringify": "^10.0.1",
        "remark-gfm": "^4.0.1",
        "styled-components": "^6.4.1",
        unified: "^11.0.5",
        zod: "^4.3.6",
      },
      devDependencies: {
        "@types/node": "^25",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        "baseline-browser-mapping": "^2.10.21",
        eslint: "^9",
        "eslint-config-next": "16.2.4",
        prettier: "^3.8.3",
        typescript: "^6",
      },
    },
    null,
    2,
  ) + "\n";
